### ISSUE TITLE
Modelled Historical Land-Use Dataset for CONUS

### ISSUE THREAD

**Issue by patdumandan** [weecology/retriever#1540]
LULC maps developed for conterminous United States from 1938 back to 1992 through hindcasting methods: https://www.sciencebase.gov/catalog/item/59d3c73de4b05fe04cc3d1d1

**Comment by Sohan022** [comment]
I have downloaded the tif files/images in a folder and run the command `retriever autocreate -dt raster -d <path of downloaded folder>`. But it is giving some error. Can you please help me creating scripts for this?

**Comment by henrykironde** [comment]
What error is it giving you ?

**Comment by Sohan022** [comment]
```
Traceback (most recent call last):
  File "/home/sohan/.local/bin/retriever", line 11, in <module>
    load_entry_point('retriever==3.0.1.dev0', 'console_scripts', 'retriever')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/sohan/.local/lib/python3.6/site-packages/retriever/__init__.py", line 7, in <module>
    from retriever.lib.engine_tools import set_proxy, create_home_dir
  File "/home/sohan/.local/lib/python3.6/site-packages/retriever/lib/__init__.py", line 4, in <module>
    from .datasets import datasets
  File "/home/sohan/.local/lib/python3.6/site-packages/retriever/lib/datasets.py", line 1, in <module>
    from retriever.lib.scripts import SCRIPT_LIST, get_script, get_dataset_names_upstream
  File "/home/sohan/.local/lib/python3.6/site-packages/retriever/lib/scripts.py", line 487, in <module>
    global_script_list = StoredScripts()
  File "/home/sohan/.local/lib/python3.6/site-packages/retriever/lib/scripts.py", line 476, in __init__
    self._shared_scripts = SCRIPT_LIST()
  File "/home/sohan/.local/lib/python3.6/site-packages/retriever/lib/scripts.py", line 114, in SCRIPT_LIST
    return reload_scripts()
  File "/home/sohan/.local/lib/python3.6/site-packages/retriever/lib/scripts.py", line 56, in reload_scripts
    read_script = read_json(join(search_path, script_name))
  File "/home/sohan/.local/lib/python3.6/site-packages/retriever/lib/load_json.py", line 30, in read_json
    file_obj = open_fr(json_file, encoding=json_file_encoding)
  File "/home/sohan/.local/lib/python3.6/site-packages/retriever/lib/tools.py", line 43, in open_fr
    file_obj = io.open(file_name, "r", encoding=encoding)
LookupError: unknown encoding: ee
```

**Comment by henrykironde** [comment]
Can you show me the command you used

**Comment by Sohan022** [comment]
> What error is it giving you ?

```
Skipped file:  CONUS_Backcasting_y1938.tif name 'gdal' is not defined
Remove the file from the folder and try again
```

**Comment by henrykironde** [comment]
You do not have Gdal installed. Install `Gdal` and let me know if you are able to run the file.
As you install Gdal, note down all the steps. We could make sure that others do not have the same issue.

After the installation, you should be able to go to Python and import Gdal using `from osgeo import gdal`

**Comment by Sohan022** [comment]
Thanks, Henry. Now, it is working
Steps for installing Gdal
```
sudo add-apt-repository ppa:ubuntugis/ppa
sudo apt-get update
sudo apt-get install gdal-bin
export CPLUS_INCLUDE_PATH=/usr/include/gdal
export C_INCLUDE_PATH=/usr/include/gdal
ogrinfo --version
pip install GDAL==<GDAL VERSION FROM OGRINFO>
```
for reference: https://mothergeo-py.readthedocs.io/en/latest/development/how-to/gdal-ubuntu-pkg.html

**Comment by Sohan022** [comment]
@henrykironde Please review my PR.
Link: https://github.com/weecology/retriever-recipes/pull/101
