### ISSUE TITLE
install fails on ubuntu

### ISSUE THREAD

**Issue by sdtaylor** [weecology/retriever#604]
I get the following error when running `pip install retriever`

```
shawn@bamboo:~$ pip install retriever
Downloading/unpacking retriever
  Downloading retriever-1.8.3.zip (123kB): 123kB downloaded
  Running setup.py (path:/tmp/pip-build-MZy553/retriever/setup.py) egg_info for package retriever
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'console'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'app'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zipfile'
      warnings.warn(msg)
    
    Failed to load script: gentry (/home/shawn/.retriever/scripts/)Compiling retriever scripts...
    done.
Downloading/unpacking xlrd (from retriever)
  Downloading xlrd-1.0.0.tar.gz (2.6MB): 2.6MB downloaded
  Running setup.py (path:/tmp/pip-build-MZy553/xlrd/setup.py) egg_info for package xlrd
    
    warning: no files found matching 'README.html'
Installing collected packages: retriever, xlrd
  Running setup.py install for retriever
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'console'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'app'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zipfile'
      warnings.warn(msg)
    
    Installing retriever script to /home/shawn/.local/bin
    Failed to load script: gentry (/home/shawn/.retriever/scripts/)Compiling retriever scripts...
    done.
  Running setup.py install for xlrd
    changing mode of build/scripts-2.7/runxlrd.py from 664 to 775
    
    warning: no files found matching 'README.html'
    changing mode of /home/shawn/.local/bin/runxlrd.py to 775
Successfully installed retriever xlrd
Cleaning up...
```

**Comment by ethanwhite** [comment]
Thanks for reporting @sdtaylor.

I see some warnings, but no errors on the install itself.

What happens if you run:

```
retriever reset all
retriever update
retriever ls
```

**Comment by sdtaylor** [comment]
Ok, it does actually install. But it gets installed inside `~/.local/` which I didn't have in my path. So it seemed like it wasn't working. Also using pip it only works with python2, python3 does have install errors. 

Henry suggested I install the latest version from github, which does work with python3

```
shawn@bamboo:~$ pip -V
pip 8.1.2 from /home/shawn/miniconda3/lib/python3.5/site-packages (python 3.5)
shawn@bamboo:~$ pip install retriever
Collecting retriever
  Using cached retriever-1.8.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nkyvjt66/retriever/setup.py", line 20, in <module>
        from __init__ import VERSION
      File "/tmp/pip-build-nkyvjt66/retriever/__init__.py", line 38
        print "The Retriever lacks permission to access the ~/.retriever/ directory."
                                                                                    ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nkyvjt66/retriever/
shawn@bamboo:~$ 
shawn@bamboo:~$ pip2 -V
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
shawn@bamboo:~$ pip2 install retriever
Downloading/unpacking retriever
  Downloading retriever-1.8.3.zip (123kB): 123kB downloaded
  Running setup.py (path:/tmp/pip-build-Z_agF6/retriever/setup.py) egg_info for package retriever
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'console'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'app'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zipfile'
      warnings.warn(msg)
    
Downloading/unpacking xlrd (from retriever)
  Downloading xlrd-1.0.0.tar.gz (2.6MB): 2.6MB downloaded
  Running setup.py (path:/tmp/pip-build-Z_agF6/xlrd/setup.py) egg_info for package xlrd
    
    warning: no files found matching 'README.html'
Installing collected packages: retriever, xlrd
  Running setup.py install for retriever
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'console'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'app'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zipfile'
      warnings.warn(msg)
    
    Installing retriever script to /home/shawn/.local/bin
    Compiling retriever scripts...
    done.
  Running setup.py install for xlrd
    changing mode of build/scripts-2.7/runxlrd.py from 664 to 775
    
    warning: no files found matching 'README.html'
    changing mode of /home/shawn/.local/bin/runxlrd.py to 775
Successfully installed retriever xlrd
Cleaning up...
shawn@bamboo:~$ 
shawn@bamboo:~$ .local/bin/retriever -v
v1.8.3
shawn@bamboo:~$ 
```

**Comment by ethanwhite** [comment]
> pip it only works with python2, python3 does have install errors

Yes, Python 3 support was only recently added and isn't in the most recent release, so direct from GitHub is the only way to get that at the moment.

> it gets installed inside ~/.local/

That's definitely not what's supposed to happen and it doesn't happen on a number of other Ubuntu machines. Is that where `pip` is installing other modules as well or is it just the retriever?

**Comment by sdtaylor** [comment]
There is nothing else in `~/.local/bin/`, so no. But I'm not a big user of pip either.

I just tried it with sudo and it installed correctly in `/usr/local/bin`

**Comment by ethanwhite** [comment]
Just looked at this locally with @sdtaylor. It was a permissions issue with using Ubuntu's Python and not installing using `sudo` (needed to put the executable in a directory on the path). If anyone else comes across this the following should solve it:

```
pip uninstall retriever
sudo pip install retriever
```
