### ISSUE TITLE
Installing BBS errors on Python 3 using SQLite

### ISSUE THREAD

**Issue by sdtaylor** [weecology/retriever#612]
I just installed the latest [build](https://github.com/weecology/retriever/tree/1a9bbb3c1564db6c6bbc2349508187f9286ed12e) and it's giving an error when downloading BBS

```
shawn@bamboo:~/projects/bbs-forecasting/data$ python -V
Python 3.5.2 :: Continuum Analytics, Inc.
shawn@bamboo:~/projects/bbs-forecasting/data$ retriever -v
v1.9.0-dev
shawn@bamboo:~/projects/bbs-forecasting/data$ retriever reset all
This will remove existing scripts, cached data, and information on database connections. Specifically it will remove the scripts and raw_data folders and the connections.config file in /home/shawn/.retriever/. Do you want to proceed? (y/N)
y
shawn@bamboo:~/projects/bbs-forecasting/data$ retriever ls
No scripts are currently available. Updating scripts now...
Downloading scripts...
Download Progress: [#######################################################################################################################################################################################################################################] 100.00%
The retriever is up-to-date


Scripts downloaded.

Available datasets : 47

Adler2007        AvianBodySize  Bioclim      DelMoral2010  FIA                Gentry      leaf_herbivory  MammalLH       MarineSize  McGlinn2010      NPN         Petraitis2008          PortalMammals  SonoranPerennials   vertnet       
AmnioteDB        BAAD           CForBioData  eBirdOD       FishParasiteHosts  GWDD        leda            MammalMR2010   Matter2014  MiscAbundanceDB  Palmer2007  PhytoplankonBiovolume  PRISM          Steppe_plants_2013  Woods2009     
Anderson2011     BBS            Clark2006    EltonTraits   FrayJorge          HomeRanges  MammalDIET      mammsupertree  MCDB        MoM2003          Pantheria   PlantTaxonomy          Ramesh2010     TreeWesternGhats    Zachmann2010  
ArcticBreedBird  BBS50          
shawn@bamboo:~/projects/bbs-forecasting/data$ 
shawn@bamboo:~/projects/bbs-forecasting/data$ retriever install sqlite BBS -f bbsforecasting.sqlite 
=> Installing USGS North American Breeding Bird Survey
Creating table BBS_species...
Saving a copy of SpeciesList.txt...
Downloading SpeciesList.txt...
Downloading /home/shawn/.retriever/raw_data/BBS/Routes.zip...
write() argument must be str, not bytes
Done!
shawn@bamboo:~/projects/bbs-forecasting/data$ 
```

**Comment by ethanwhite** [comment]
This looks like an issue with the new Python 3 support. @goelakash - can you take a look at this if you have a few minutes?

**Comment by ethanwhite** [comment]
Thanks for reporting this @sdtaylor and for the really nice bug report!

**Comment by sdtaylor** [comment]
debug output for @henrykironde 

```
shawn@bamboo:~$ retriever install --debug csv bbs
=> Installing USGS North American Breeding Bird Survey
write() argument must be str, not bytes6 / 746
Traceback (most recent call last):
  File "/home/shawn/miniconda3/bin/retriever", line 9, in <module>
    load_entry_point('retriever===1.9.0-de', 'console_scripts', 'retriever')()
  File "/home/shawn/miniconda3/lib/python3.5/site-packages/retriever-1.9.0_de-py3.5.egg/retriever/__main__.py", line 172, in main
    dataset.download(engine, debug=debug)
  File "/home/shawn/.retriever/scripts/bbs.py", line 66, in download
    engine.download_files_from_archive(self.urls["routes"], ["routes.csv"])
  File "/home/shawn/miniconda3/lib/python3.5/site-packages/retriever-1.9.0_de-py3.5.egg/retriever/lib/engine.py", line 458, in download_files_from_archive
    unzipped_file.write(line)
TypeError: write() argument must be str, not bytes
shawn@bamboo:~$
```

**Comment by goelakash** [comment]
@ethanwhite I get a different error log:
```
Downloading /home/goelakash/.retriever/raw_data/BBS/Weather.zip...
[Errno ftp error] 200 Switching to Binary mode.
Traceback (most recent call last):
  File "/usr/local/bin/retriever", line 9, in <module>
    load_entry_point('retriever===1.9.0-de', 'console_scripts', 'retriever')()
  File "/usr/local/lib/python2.7/dist-packages/retriever-1.9.0_de-py2.7.egg/retriever/__main__.py", line 135, in main
    dataset.download(engine, debug=debug)
  File "/home/goelakash/.retriever/scripts/bbs.py", line 75, in download
    ["weather.csv"])
  File "/usr/local/lib/python2.7/dist-packages/retriever-1.9.0_de-py2.7.egg/retriever/lib/engine.py", line 440, in download_files_from_archive
    self.download_file(url, archivename)
  File "/usr/local/lib/python2.7/dist-packages/retriever-1.9.0_de-py2.7.egg/retriever/lib/engine.py", line 413, in download_file
    urlretrieve(url, path)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 558, in open_ftp
    (fp, retrlen) = self.ftpcache[key].retrfile(file, type)
  File "/usr/lib/python2.7/urllib.py", line 906, in retrfile
    conn, retrlen = self.ftp.ntransfercmd(cmd)
  File "/usr/lib/python2.7/ftplib.py", line 334, in ntransfercmd
    host, port = self.makepasv()
  File "/usr/lib/python2.7/ftplib.py", line 312, in makepasv
    host, port = parse227(self.sendcmd('PASV'))
  File "/usr/lib/python2.7/ftplib.py", line 830, in parse227
    raise error_reply, resp
IOError: [Errno ftp error] 200 Switching to Binary mode.
```

**Comment by ethanwhite** [comment]
@goelakash - I get that at home, but not at work. I was wondering if maybe I'd gotten firewalled for hitting their servers too much. Regardless, this is definitely a separate issue.

Can you download the relevant files manually into the `~/.retriever/raw_data/BBS` directory to explore this issue? When I hit this error I was able to do that last time.

Could you also open an issue on the error you're getting so that we can figure out if that's just you and me or if it's a broader issue? Thanks.

**Comment by ethanwhite** [comment]
I've updated the title to reflect that this is a Python 3 issue and am moving @goelakash's report into a separate issue.

**Comment by ethanwhite** [comment]
This is the same issue as #668. Since it's more general than BBS I'm going to go ahead and close this one. Henry should be finished fixing #668 shortly.
