### ISSUE TITLE
Errors  on BBS

### ISSUE THREAD

**Issue by ethanwhite** [weecology/retriever#622]
As reported in #612 by @goelakash, in some cases when installing the BBS data we receive an FTP error: `IOError: [Errno ftp error] 200 Switching to Binary mode.`

I have seen this error on Ubuntu 16.04, Python 2.7. The error occurred on the same machine both at my house and on the wireless at UF. Installing BBS works fine on my work Desktop (Ubuntu 15.04, Python 2.7) which would seem to suggest that this is not an issue with being firewalled from too much testing as I'd originally assumed.

```
Downloading /home/goelakash/.retriever/raw_data/BBS/Weather.zip...
[Errno ftp error] 200 Switching to Binary mode.
Traceback (most recent call last):
  File "/usr/local/bin/retriever", line 9, in <module>
    load_entry_point('retriever===1.9.0-de', 'console_scripts', 'retriever')()
  File "/usr/local/lib/python2.7/dist-packages/retriever-1.9.0_de-py2.7.egg/retriever/__main__.py", line 135, in main
    dataset.download(engine, debug=debug)
  File "/home/goelakash/.retriever/scripts/bbs.py", line 75, in download
    ["weather.csv"])
  File "/usr/local/lib/python2.7/dist-packages/retriever-1.9.0_de-py2.7.egg/retriever/lib/engine.py", line 440, in download_files_from_archive
    self.download_file(url, archivename)
  File "/usr/local/lib/python2.7/dist-packages/retriever-1.9.0_de-py2.7.egg/retriever/lib/engine.py", line 413, in download_file
    urlretrieve(url, path)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 558, in open_ftp
    (fp, retrlen) = self.ftpcache[key].retrfile(file, type)
  File "/usr/lib/python2.7/urllib.py", line 906, in retrfile
    conn, retrlen = self.ftp.ntransfercmd(cmd)
  File "/usr/lib/python2.7/ftplib.py", line 334, in ntransfercmd
    host, port = self.makepasv()
  File "/usr/lib/python2.7/ftplib.py", line 312, in makepasv
    host, port = parse227(self.sendcmd('PASV'))
  File "/usr/lib/python2.7/ftplib.py", line 830, in parse227
    raise error_reply, resp
IOError: [Errno ftp error] 200 Switching to Binary mode.
```

**Comment by henrykironde** [comment]
I am able to download bbs fine. I think they put a temp firewall which shouldn't be a big issue for users. This could be solved by mimicking a browser request but I think its not useful. This could be  solution if that persists for long. On the other hand, we should keep local copies of BBS for testing so that we do not over use their resources.

**Comment by ethanwhite** [comment]
This is the same as #705. Since the more recent issue is tied in to some other discussions I'm going to close this one.
