### ISSUE TITLE
Installs into sqlite failing on Windows 10, Python 2.7

### ISSUE THREAD

**Issue by emchristensen** [weecology/retriever#773]
I get an error when trying to run command "retriever install sqlite wine-quality" (same problem with wood-density too)
installing as csv, json, or xml works fine
running on windows 10, using python 2.7

```
Error message:
Traceback (most recent call last):
  File "C:\Users\EC\Anaconda\Scripts\retriever-script.py", line 9, in <module>
    load_entry_point('retriever==2.0.dev0', 'console_scripts', 'retriever')()
  File "c:\users\ec\anaconda\lib\site-packages\retriever\__main__.py", line 175, in main
    dataset.download(engine, debug=debug)
  File "c:\users\ec\anaconda\lib\site-packages\retriever\lib\templates.py", line 102, in download
    self.engine.insert_data_from_url(value)
  File "c:\users\ec\anaconda\lib\site-packages\retriever\lib\engine.py", line 632, in insert_data_from_url
    self.insert_data_from_file(find)
  File "c:\users\ec\anaconda\lib\site-packages\retriever\lib\engine.py", line 624, in insert_data_from_file
    self.add_to_table(data_source)
  File "c:\users\ec\anaconda\lib\site-packages\retriever\lib\engine.py", line 116, in add_to_table
    self.execute(insert_stmt, commit=False)
  File "c:\users\ec\anaconda\lib\site-packages\retriever\lib\engine.py", line 480, in execute
    self.cursor.execute(statement)
sqlite3.OperationalError: near ",": syntax error
```

**Comment by ethanwhite** [comment]
Thanks @emchristensen. Are those two datasets the only two you tried using SQLite or were some things installing successfully?

Also, can you open Python run the following and let us know what it returns:

```
import sqlite3
sqlite3.sqlite_version
```

Thanks!

**Comment by henrykironde** [comment]
Yes this looks like an sqlite3 version problem. Very old sqlite3 versions will not work. Update and let me know if the error prevails. I did not update docs because the versions that don't work end in 2013.

**Comment by emchristensen** [comment]
It says I have version 3.6.21

**Comment by emchristensen** [comment]
And I just tried it with a few more datasets, I get the same "syntax error" with all of them.

**Comment by ethanwhite** [comment]
Thanks @emchristensen. The version is definitely the issue. Now we just need to figure out why such an old version is getting distributed with Anaconda Python...

**Comment by emchristensen** [comment]
I deleted and re-installed Anaconda, and now it works!

**Comment by henrykironde** [comment]
Could you check the version again?

**Comment by emchristensen** [comment]
3.8.11

**Comment by ethanwhite** [comment]
I had Morgan update her Python and that took care of it as well. Thanks for the help @emchristensen!
